Mouse UI
MLH-Fellowship/pod-3.1.1-portfolio pull request #16
Opened 2021-07-21 10:25 UTC by hkaur008

Things added so far:-
- Add a mouse interactive UI background

Reasons to add:-
- To viewers helps to gain more interest in the portfolio.

## Please, go through these steps before you submit a PR.
- [X] You've explained what the Pull Request is adding.
- [X] You've explained why this is important.
#Fixes issue 15

2021-07-21 13:24 UTC, rosekamallove requested changes
Please change hard coded color value to one of the variables in _sass/theme.scss

2021-07-21 13:24 UTC, rosekamallove commented on _sass/all.scss
> +        color: #404040;
Adding one of the variables instead of hard coded value would be better.

2021-07-21 13:30 UTC, rosekamallove commented
This and PR #14 seem to have the same file changes and commits.

2021-07-21 14:05 UTC, hkaur008 commented
> This and PR #14 seem to have the same file changes and commits.

opps i just forget to commit and add some files

2021-07-21 14:13 UTC, hkaur008 commented
yeah implemented things out !

2021-07-22 12:26 UTC, awilkescom commented
Hey @hkaur008 , I couldn't get this working

for some reason i get an error in chrome to load a JS file it seems,

![image](https://user-images.githubusercontent.com/49675331/126638681-9e35a2ca-6f23-48cf-86ad-996faf806d3a.png)

Also I think for something visual, it would be worth to include a screenshot in your PR so it's clear what to look for. 

Could you see if you can debug this issue and update the PR ? thanks

2021-07-22 12:27 UTC, awilkescom commented
Ok, the error with the JS file resolved itself, but I can't see any visual change

2021-07-22 12:36 UTC, hkaur008 commented
hey @awilkescom let me check again , i think there is were some pull request merged before which caused conflicts

2021-07-22 12:57 UTC, hkaur008 commented
hey ! @awilkescom  . you can check now

2021-07-22 13:01 UTC, awilkescom commented
I really like it, nice effect! Thanks @hkaur008 !

2021-07-22 13:01 UTC, merged