Contactinfo
MLH-Fellowship/pod-3.1.1-portfolio pull request #24
Opened 2021-07-22 13:49 UTC by shivamsouravjha

What I've done:-
- I've added a contact info form where the viewer can enter the name, mail, message and send an email to contact us.
Why have I done:
- In order to enable viewers to have conversations with the portfolio creators.
## Please, go through these steps before you submit a PR.

- [X] You've explained what the Pull Request is adding.
- [X] You've explained why this is important.

Closes #5 

CC @hkaur008 for review/suggestion.

2021-07-22 13:50 UTC, shivamsouravjha commented
I'm trying to resolve the errors.

2021-07-22 14:06 UTC, hkaur008 approved these changes

2021-07-22 16:18 UTC, hkaur008 commented
@shivamsouravjha  are these resolved ?

2021-07-22 16:58 UTC, shivamsouravjha commented
@hkaur008 yes resolved!

2021-07-22 17:01 UTC, rosekamallove requested changes
![Screenshot from 2021-07-22 22-20-23](https://user-images.githubusercontent.com/69139607/126678227-7d2c2af1-fcb6-429e-8559-e4089e49541d.png)

- The card just disappears with the background and is not in line with the rest of the.
- What you can do @KUHOO-S had the idea, you can just make it blend with the background.
- Maybe use `bootstrap classes` to style the `input fields` and `submit buttons`

2021-07-22 17:01 UTC, rosekamallove commented on _sass/contact.scss
> +	background-color: var(--secondaryColor);
You should use the variables present in `_sass/theme.scss` and add more variables if needer.

2021-07-22 17:01 UTC, rosekamallove commented on _sass/all.scss
> +        color: #404040;
Here too

2021-07-22 17:01 UTC, rosekamallove commented on _sass/contact.scss
> +    background-color: var(--mainColor);
This background color doesn't seem to look good, again _use already created variables_ this just disappears with the background.

2021-07-22 17:37 UTC, shivamsouravjha commented on _sass/contact.scss
> +    background-color: var(--mainColor);
That's some cool idea,let me update it.

2021-07-22 18:01 UTC, shivamsouravjha commented
@rosekamallove Idk why I'm getting this bug ,any clue about this? 
![Screenshot (276)](https://user-images.githubusercontent.com/60891544/126686837-9cbe8522-6c5a-4f92-b332-b7553b423a5e.png)

2021-07-22 18:08 UTC, rosekamallove commented
Yeah, you don't really need to worry about it if it's not causing any problem in the functionality of your PR. I fixed it already in my PR yesterday.

2021-07-22 18:49 UTC, shivamsouravjha commented
yeah yeah, I remember the suggestion thing, cool if it's fixed then.

2021-07-23 08:13 UTC, awilkescom commented
Hey, whats the expected behaviour for this? 

For me, it opens my email client and creates an example message

Put it buts the name and email in the content of the message.

How does the portfolio author change the email to be sent to ?

I think we just need to document the feature a bit better so it's clear what to expect from this change

![image](https://user-images.githubusercontent.com/49675331/126754621-3459aba2-2601-43b4-bc9a-78b0e5f99db2.png)

2021-07-23 08:51 UTC, shivamsouravjha commented
@awilkescom so this feature is a way for the visitor to contact the portfolio owner, and yes this is the desired behaviour of the email. I will comment on the area from where we can change the email.

2021-07-23 12:34 UTC, awilkescom commented
Ok, thanks!

2021-07-23 12:34 UTC, merged